const selecciones = {
    0: {
        pais: "Alemania",
        colorPrincipal: "#000000",
        colorSecundario: "#FF0000",
        historia: "Cuatro veces campeona del mundo, Alemania es sinónimo de potencia futbolística y garra.",
        modelo3D: "0",
    },
    1: {
        pais: "Arabia Saudita",
        colorPrincipal: "#006C35",
        colorSecundario: "#FFFFFF",
        historia: "Potencia asiática conocida por su velocidad y técnica, han logrado victorias históricas en mundiales.",
        modelo3D: "1",
    },
    2: {
        pais: "Argelia",
        colorPrincipal: "#006633",
        colorSecundario: "#FFFFFF",
        historia: "Los Zorros del Desert, representantes africanos con gran técnica y orgullo.",
        modelo3D: "2",
    },
    3: {
        pais: "Argentina",
        colorPrincipal: "#75AADB",
        colorSecundario: "#FFFFFF",
        historia: "Campeones del mundo, liderados por figuras históricas que marcan época.",
        modelo3D: "3",
    },
    4: {
        pais: "Australia",
        colorPrincipal: "#FCD116",
        colorSecundario: "#008751",
        historia: "Los Socceroos, conocidos por su garra física y su constante crecimiento.",
        modelo3D: "4",
    },
    5: {
        pais: "Austria",
        colorPrincipal: "#ED2939",
        colorSecundario: "#FFFFFF",
        historia: "Selección europea de tradición, con jugadores técnicos y orden táctico.",
        modelo3D: "5",
    },
    6: {
        pais: "Bélgica",
        colorPrincipal: "#E03A3E",
        colorSecundario: "#FDDA25",
        historia: "La generación dorada belga siempre promete un fútbol vistoso y ofensivo.",
        modelo3D: "6",
    },
    7: {
        pais: "Brasil",
        colorPrincipal: "#FEDF00",
        colorSecundario: "#009B3A",
        historia: "La pentacampeona, sinónimo de fútbol arte, jogo bonito y estrellas eternas.",
        modelo3D: "7",
    },
    8: {
        pais: "Cabo Verde",
        colorPrincipal: "#003893",
        colorSecundario: "#FFFFFF",
        historia: "Los Tiburones Azules, una revelación africana con mucho talento emergente.",
        modelo3D: "8",
    },
    9: {
        pais: "Canadá",
        colorPrincipal: "#FF0000",
        colorSecundario: "#FFFFFF",
        historia: "Coanfitriones con una nueva generación que promete hacer historia local.",
        modelo3D: "9",
    },
    10: {
        pais: "Colombia",
        colorPrincipal: "#FCD116",
        colorSecundario: "#003893",
        historia: "La Selección de la esperanza, conocida por su garra, talento y pasión.",
        modelo3D: "10",
    },
    11: {
        pais: "Corea del Sur",
        colorPrincipal: "#C60C30",
        colorSecundario: "#0047A0",
        historia: "Semifinalistas en 2002, son el equipo asiático con más participaciones mundialistas.",
        modelo3D: "11",
    },
    12: {
        pais: "Costa de Marfil",
        colorPrincipal: "#F77F00",
        colorSecundario: "#009E60",
        historia: "Los Elefantes, campeones africanos con una generación histórica de jugadores.",
        modelo3D: "12",
    },
    13: {
        pais: "Croacia",
        colorPrincipal: "#C8102E",
        colorSecundario: "#FFFFFF",
        historia: "Subcampeona en 2018, los ajedrezados son un ejemplo de resiliencia y calidad.",
        modelo3D: "13",
    },
    14: {
        pais: "Curazao",
        colorPrincipal: "#003DA5",
        colorSecundario: "#FEDD00",
        historia: "La sorpresa caribeña que ha crecido gracias a jugadores con raíces neerlandesas.",
        modelo3D: "14",
    },
    15: {
        pais: "Ecuador",
        colorPrincipal: "#FEDF00",
        colorSecundario: "#09347A",
        historia: "La Tri, conocida por su altura en Quito y su fútbol vibrante en los últimos mundiales.",
        modelo3D: "15.png",
    },
    16: {
        pais: "Egipto",
        colorPrincipal: "#C8102E",
        colorSecundario: "#FFFFFF",
        historia: "Los Faraones, liderados por grandes figuras, son el orgullo del fútbol africano.",
        modelo3D: "16",
    },
    17: {
        pais: "Escocia",
        colorPrincipal: "#003876",
        colorSecundario: "#FFFFFF",
        historia: "La histórica selección británica con una afición que nunca deja de alentar.",
        modelo3D: "17",
    },
    18: {
        pais: "España",
        colorPrincipal: "#C60B1E",
        colorSecundario: "#FFC400",
        historia: "La Roja, campeona del mundo 2010, revolucionó el fútbol con su estilo de toque.",
        modelo3D: "18",
    },
    19: {
        pais: "Estados Unidos",
        colorPrincipal: "#3C3B6E",
        colorSecundario: "#B22234",
        historia: "Coanfitriones con una selección joven que busca consolidarse entre las potencias.",
        modelo3D: "19",
    },
    20: {
        pais: "Francia",
        colorPrincipal: "#002395",
        colorSecundario: "#FFFFFF",
        historia: "Bicampeones del mundo, los Bleus combinan talento joven con experiencia ganadora.",
        modelo3D: "20",
    },
    21: {
        pais: "Ghana",
        colorPrincipal: "#C8102E",
        colorSecundario: "#FCD116",
        historia: "Las Estrellas Negras, un clásico africano que siempre da batalla en los mundiales.",
        modelo3D: "21",
    },
    22: {
        pais: "Haití",
        colorPrincipal: "#00209F",
        colorSecundario: "#D21034",
        historia: "El primer equipo caribeño en clasificar a un mundial, con garra y orgullo.",
        modelo3D: "22",
    },
    23: {
        pais: "Inglaterra",
        colorPrincipal: "#FFFFFF",
        colorSecundario: "#C8102E",
        historia: "La cuna del fútbol, campeona en 1966 y siempre en la pelea por el título.",
        modelo3D: "23",
    },
    24: {
        pais: "Irán",
        colorPrincipal: "#239F40",
        colorSecundario: "#FFFFFF",
        historia: "Potencia asiática, conocida por su orden táctico y resistencia física.",
        modelo3D: "24",
    },
    25: {
        pais: "Japón",
        colorPrincipal: "#000066",
        colorSecundario: "#FFFFFF",
        historia: "Los Samuráis Azules, ejemplo de disciplina, técnica y constante evolución.",
        modelo3D: "25",
    },
    26: {
        pais: "Jordania",
        colorPrincipal: "#CE1126",
        colorSecundario: "#FFFFFF",
        historia: "Selección asiática en crecimiento, buscando dejar su huella en el mundo.",
        modelo3D: "26",
    },
    27: {
        pais: "Marruecos",
        colorPrincipal: "#C1272D",
        colorSecundario: "#006233",
        historia: "Los Leones del Atlas, hicieron historia siendo el primer africano en semifinales.",
        modelo3D: "27",
    },
    28: {
        pais: "México",
        colorPrincipal: "#006847",
        colorSecundario: "#CE1126",
        historia: "Anfitrión histórico, con una afición única y tradición de quinto partido.",
        modelo3D: "28",
    },
    29: {
        pais: "Mundial 2026",
        colorPrincipal: "#FFD100",
        colorSecundario: "#041E42",
        historia: "La celebración del fútbol en Norteamérica, uniendo tres países anfitriones.",
        modelo3D: "29",
    },
    30: {
        pais: "Noruega",
        colorPrincipal: "#BA0C2F",
        colorSecundario: "#FFFFFF",
        historia: "Los Vikingos, con una historia de garra y jugadores que marcaron época.",
        modelo3D: "30",
    },
    31: {
        pais: "Nueva Zelanda",
        colorPrincipal: "#000000",
        colorSecundario: "#FFFFFF",
        historia: "Los All Whites, representantes de Oceanía con espíritu combativo.",
        modelo3D: "31",
    },
    32: {
        pais: "Países Bajos",
        colorPrincipal: "#F36C21",
        colorSecundario: "#FFFFFF",
        historia: "La Naranja Mecánica, tres veces subcampeona, sinónimo de fútbol total.",
        modelo3D: "32",
    },
    33: {
        pais: "Panamá",
        colorPrincipal: "#0055A4",
        colorSecundario: "#FFFFFF",
        historia: "Los Canaleros, debutantes en 2018, representan el crecimiento centroamericano.",
        modelo3D: "33",
    },
    34: {
        pais: "Paraguay",
        colorPrincipal: "#D52B1E",
        colorSecundario: "#FFFFFF",
        historia: "Los Guaraníes, conocidos por su garra defensiva y su fútbol de lucha.",
        modelo3D: "34",
    },
    35: {
        pais: "Portugal",
        colorPrincipal: "#FF0000",
        colorSecundario: "#006600",
        historia: "Campeona de Europa, con una generación dorada y figuras legendarias.",
        modelo3D: "35",
    },
    36: {
        pais: "Qatar",
        colorPrincipal: "#75002B",
        colorSecundario: "#FFFFFF",
        historia: "Anfitriones recientes, con un proyecto deportivo en constante crecimiento.",
        modelo3D: "36",
    },
    37: {
        pais: "Senegal",
        colorPrincipal: "#00853F",
        colorSecundario: "#FDE100",
        historia: "Los Leones de la Teranga, campeones africanos con garra y calidad.",
        modelo3D: "37",
    },
    38: {
        pais: "Sudáfrica",
        colorPrincipal: "#F2A900",
        colorSecundario: "#007A4D",
        historia: "Los Bafana Bafana, anfitriones en 2010, orgullo del fútbol africano.",
        modelo3D: "38",
    },
    39: {
        pais: "Suiza",
        colorPrincipal: "#FF0000",
        colorSecundario: "#FFFFFF",
        historia: "La Nati, conocida por su orden táctico y solidez defensiva en torneos.",
        modelo3D: "39",
    },
    40: {
        pais: "Túnez",
        colorPrincipal: "#E70013",
        colorSecundario: "#FFFFFF",
        historia: "Las Águilas de Cartago, el equipo árabe con más participaciones mundialistas.",
        modelo3D: "40",
    },
    41: {
        pais: "Uruguay",
        colorPrincipal: "#0038A8",
        colorSecundario: "#FEDD00",
        historia: "La Celeste, primera campeona del mundo, con garra y tradición de sobra.",
        modelo3D: "41",
    },
    42: {
        pais: "Uzbekistán",
        colorPrincipal: "#0099B5",
        colorSecundario: "#FFFFFF",
        historia: "Los Lobos Blancos, una selección asiática en ascenso hacia la élite.",
        modelo3D: "42",
    },
    43: {
        pais: "Chile",
        colorPrincipal: "#E70013",
        colorSecundario: "#FFFFFF",
        historia: "Su 'Generación Dorada' hizo historia grande al ganar dos Copas América consecutivas",
        modelo3D: "43",
    },
    44: {
        pais: "Costa Rica",
        colorPrincipal: "#ff0000",
        colorSecundario: "#FEDD00",
        historia: "Dieron la gran sorpresa en el Mundial de 2014. Ganaron el 'Grupo de la Muerte' (superando a Uruguay, Italia e Inglaterra)",
        modelo3D: "44",
    },
    45: {
        pais: "Italia",
        colorPrincipal: "#bd1212",
        colorSecundario: "#2b9022",
        historia: "Aparte de sus 4 Copas del Mundo, tienen un récord histórico impresionante: la racha invicta más larga en el fútbol internacional, con 37 partidos seguidos sin perder entre 2018 y 2021.",
        modelo3D: "45",
    },
    46: {
        pais: "Polonia",
        colorPrincipal: "#E70013",
        colorSecundario: "#FFFFFF",
        historia: "Hoy en día, todos sus récords de goles le pertenecen a Robert Lewandowski",
        modelo3D: "46",
    },
    47: {
        pais: "Suecia",
        colorPrincipal: "#0038A8",
        colorSecundario: "#FEDD00",
        historia: "Organizaron el Mundial de 1958 y llegaron a la final, pero perdieron contra un jovencísimo Pelé que jugaba para Brasil. Su leyenda moderna y máximo goleador es Zlatan Ibrahimović",
        modelo3D: "47",
    },
    48: {
        pais: "Ucrania",
        colorPrincipal: "#ffe600",
        colorSecundario: "#129fb5",
        historia: "En su primera y única participación en un Mundial como país independiente (Alemania 2006), sorprendieron a todos llegando hasta los cuartos de final, liderados por el histórico delantero Andriy Shevchenko.",
        modelo3D: "48",
    }
};